import {Router} from 'express';
import term from '../controllers/termController';
// import router from './classRouter';
const route = Router();
route.get('/',term.getAll);
route.get('/:id',term.getParticulars);
route.get('/p/:classId/:term/:course',term.getParticularsPerClass);
route.get('/:studentId/:term/:classId',term.getMarksForReport);
route.put('/:id',term.updateTerm);
route.delete('/:id',term.deleteTerm);
route.post('/',term.addNewRecord);
export default route;